# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb",
         "parse_artists_tags": "00_core.ipynb",
         "parse_user_artists_matrix": "00_core.ipynb",
         "objective_fcn": "00_core.ipynb",
         "setup_device_coords": "00_core.ipynb",
         "plot_sunspots": "00_core.ipynb",
         "segment_lengths": "00_core.ipynb",
         "segment_orientations": "00_core.ipynb"}

modules = ["core.py",
           "None.py"]

doc_url = "https://arlingva.github.io/hola_nbdev/"

git_url = "https://github.com/arlingva/hola_nbdev/tree/master/"

def custom_doc_links(name): return None
